### model
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 256
lora_target: all
pref_beta: 0.1

### dataset
dataset: messy_reasoning_0.7_big
template: llama3
cutoff_len: 16384
max_samples: 1000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/taco-ll3-8B-llama-8b-slerp-0.7-big-lora-256-epochs-2
logging_steps: 1
save_steps: 50
plot_loss: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 12
learning_rate: 1.0e-5
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

# report_to: wandb
run_name: Sky-T1


